In [1]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings("ignore")
pd.set_option("display.max_columns",None)

In [2]:
training_data=pd.read_csv("cars_train.csv",header=None)
testing_data=pd.read_csv("cars_test.csv" ,header=None)
print(training_data.shape)
print(testing_data.shape)

(1382, 7)
(346, 7)


In [3]:
training_data.columns=["buying","maint","doors","persons","lug_boot","safety","classes"]
testing_data.columns=["buying","maint","doors","persons","lug_boot","safety","classes"]

In [4]:
training_data.head()

buying  maint  doors persons lug_boot safety classes
0  vhigh   high      3    more    small    low   unacc
1    low  vhigh      3       4    small    med   unacc
2    low   high  5more    more      big    low   unacc
3   high    med      4       2    small    med   unacc
4    low    low      3    more      big    med    good

In [5]:
print(training_data.isnull().sum())
print("!!!!!!!!!!!!")
print(testing_data.isnull().sum())

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
classes     0
dtype: int64
!!!!!!!!!!!!
buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
classes     0
dtype: int64


In [6]:
testing_data.drop("classes",inplace=True,axis=1)
testing_data.head()

buying  maint  doors persons lug_boot safety
0    med  vhigh  5more       4    small    low
1  vhigh   high      2       2      big    med
2    low   high      2    more    small    low
3  vhigh  vhigh      3       2      big   high
4    low    med      4       4      med    med

In [7]:
colname=training_data.columns
colname

Index(['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'classes'], dtype='object')

In [8]:
from sklearn import  preprocessing
le=preprocessing.LabelEncoder()
for x in  colname:
  training_data[x]=le.fit_transform(training_data[x])

In [9]:
training_data.head()

buying  maint  doors  persons  lug_boot  safety  classes
0       3      0      1        2         2       1        2
1       1      3      1        1         2       2        2
2       1      0      3        2         0       1        2
3       0      2      2        0         2       2        2
4       1      1      1        2         0       2        1

In [10]:
from sklearn import  preprocessing
colname=testing_data.columns
for x in  colname:
  testing_data[x]=le.fit_transform(testing_data[x])

In [11]:
X = training_data.values[:,0:-1]
Y = training_data.values[:,-1]

In [12]:
X.shape

(1382, 6)

In [13]:
Y.shape

(1382,)

In [14]:
from sklearn.preprocessing import StandardScaler

scaler=StandardScaler()
scaler.fit(X)
X=scaler.transform(X)

In [15]:
from sklearn.model_selection import train_test_split
X_train,X_test, Y_train,Y_test = train_test_split(X,Y,test_size=0.2,random_state=10)

In [16]:
from sklearn.tree import DecisionTreeClassifier
model_DecisionTree=DecisionTreeClassifier(criterion="gini",random_state=10)
model_DecisionTree.fit(X_train,Y_train)
Y_pred=model_DecisionTree.predict(X_test)

In [17]:
print(list(zip(Y_test,Y_pred)))

[(2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (1, 1), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (0, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (0, 0), (1, 0), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (3, 3), (0, 0), (2, 2), (0, 0), (3, 3), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (1, 0), (2, 2), (0, 0), (0, 0), (2, 2), (2, 2), (0, 0), (3, 3), (0, 0), (0, 0), (2, 2), (2, 2), (0, 0), (2, 2), (0, 0), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (0, 0), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (0, 0), (3, 3), (2, 2), (2, 2), (0, 0), (0, 0), (2, 2), (2, 2), (2, 2), (0, 0), (2, 2), (0, 0), (3, 3), (2, 2), (0, 0), (3, 3), (2, 2), (2, 2), (2, 2), (2, 2), (2, 2), (3, 3), (2, 2), (0, 0), (2, 2), (0, 0),

In [18]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))


[[ 69   1   1   0]
 [  4   8   0   0]
 [  0   0 185   0]
 [  0   0   0   9]]
              precision    recall  f1-score   support

           0       0.95      0.97      0.96        71
           1       0.89      0.67      0.76        12
           2       0.99      1.00      1.00       185
           3       1.00      1.00      1.00         9

    accuracy                           0.98       277
   macro avg       0.96      0.91      0.93       277
weighted avg       0.98      0.98      0.98       277

0.9783393501805054


In [19]:
model_DecisionTree.score(X_train, Y_train)

1.0

In [20]:
# Feature selection
print(sorted(list(zip(testing_data.columns[0:-1],model_DecisionTree.feature_importances_))))

[('buying', 0.21976792783843332), ('doors', 0.062005934167191426), ('lug_boot', 0.09772725134941933), ('maint', 0.18220929667385857), ('persons', 0.19425872158174767)]


In [21]:
sample=pd.DataFrame()
sample["column"]=training_data.columns[0:-1]
sample["Imp value"]=model_DecisionTree.feature_importances_
sample.sort_values("Imp value", ascending=False)

column  Imp value
5    safety   0.244031
0    buying   0.219768
3   persons   0.194259
1     maint   0.182209
4  lug_boot   0.097727
2     doors   0.062006

In [22]:
from sklearn import tree
with open(r"model_DecisionTree.txt", "w") as f:
  f= tree.export_graphviz(model_DecisionTree, feature_names=training_data.columns[0:-1],out_file=f)
# generate the file and upload the code in webgraphviz.com to plot the decision tree

In [23]:
from sklearn import tree
with open(r"model_DecisionTree.txt","w") as f:

  f=tree.export_graphviz(model_DecisionTree, feature_names=training_data.columns[0:-1],out_file=f)

 #generate file & upload the code in webgraphiz.com to plot dt

In [24]:
#Prooning
from sklearn.tree import DecisionTreeClassifier
model_DecisionTree = DecisionTreeClassifier(criterion="gini",random_state=10,
                                             splitter="best",
                                             max_depth=10,
                                             min_samples_leaf=5,
                                             min_samples_split=10)
model_DecisionTree.fit(X_train,Y_train)
y_pred=model_DecisionTree.predict(X_test)

#min_samples_split – Minimum number of samples a node must possess before splitting.
#min_samples_leaf – Minimum number of samples a leaf node must possess.
#splitter - features with highest importance (random or best)
#criterion - gini or entropy

In [25]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import LogisticRegression

# first, initialize the classificators
tree= DecisionTreeClassifier(random_state=10) # using the random state for reproducibility
knn= KNeighborsClassifier(n_neighbors=5,metric='euclidean')
svm= SVC(kernel="rbf", gamma=0.1, C=1,random_state=10)
logreg=LogisticRegression(multi_class="multinomial",random_state=10)

In [26]:
models=[tree,knn,svm,logreg]

In [27]:
from sklearn.metrics import confusion_matrix, accuracy_score,classification_report

for model in models:
    model.fit(X_train, Y_train) # fit the model
    Y_pred= model.predict(X_test) # then predict on the test set
    accuracy= accuracy_score(Y_test, Y_pred)
    clf_report= classification_report(Y_test, Y_pred)
    print(confusion_matrix(Y_test,Y_pred))
    print("The accuracy of the ",type(model).__name__, " model is ", accuracy*100 )
    print("Classification report:\n", clf_report)
    print("\n")

[[ 69   1   1   0]
 [  4   8   0   0]
 [  0   0 185   0]
 [  0   0   0   9]]
The accuracy of the  DecisionTreeClassifier  model is  97.83393501805054
Classification report:
               precision    recall  f1-score   support

           0       0.95      0.97      0.96        71
           1       0.89      0.67      0.76        12
           2       0.99      1.00      1.00       185
           3       1.00      1.00      1.00         9

    accuracy                           0.98       277
   macro avg       0.96      0.91      0.93       277
weighted avg       0.98      0.98      0.98       277



[[ 65   1   5   0]
 [  8   4   0   0]
 [  1   0 184   0]
 [  2   0   1   6]]
The accuracy of the  KNeighborsClassifier  model is  93.50180505415162
Classification report:
               precision    recall  f1-score   support

           0       0.86      0.92      0.88        71
           1       0.80      0.33      0.47        12
           2       0.97      0.99      0.98       185


In [28]:
from sklearn.svm import SVC

svc_model=SVC(kernel='rbf',C=90,gamma=0.1)
svc_model.fit(X_train,Y_train)

SVC(C=90, gamma=0.1)

In [29]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

Y_pred_new=svc_model.predict(X_test)

print(confusion_matrix(Y_test,Y_pred_new))
print(classification_report(Y_test,Y_pred_new))
print(accuracy_score(Y_test,Y_pred_new))

[[ 69   0   2   0]
 [  2  10   0   0]
 [  0   0 185   0]
 [  0   0   0   9]]
              precision    recall  f1-score   support

           0       0.97      0.97      0.97        71
           1       1.00      0.83      0.91        12
           2       0.99      1.00      0.99       185
           3       1.00      1.00      1.00         9

    accuracy                           0.99       277
   macro avg       0.99      0.95      0.97       277
weighted avg       0.99      0.99      0.99       277

0.9855595667870036


In [30]:
test=scaler.transform(testing_data)

In [31]:
from sklearn.tree import DecisionTreeClassifier
model_DecisionTree=DecisionTreeClassifier(criterion="gini",random_state=10)
model_DecisionTree.fit(X_train,Y_train)
Y_pred=model_DecisionTree.predict(test)
Y_pred

array([2, 2, 2, 2, 1, 2, 0, 0, 2, 0, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 3,
       2, 0, 2, 2, 2, 2, 2, 0, 1, 3, 1, 2, 0, 2, 0, 2, 2, 2, 2, 3, 2, 2,
       0, 0, 2, 2, 3, 2, 2, 2, 1, 2, 0, 3, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0,
       2, 0, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 1, 2, 2, 0, 2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 0, 2, 2, 3, 2, 2, 0, 2, 0, 3, 2, 2, 2, 2, 2, 2, 2, 2, 3, 2,
       2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 0, 2, 3, 2, 2,
       2, 2, 0, 0, 2, 2, 2, 2, 3, 2, 0, 2, 1, 0, 2, 2, 2, 2, 2, 3, 0, 0,
       2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 2, 2, 3, 0, 2, 2, 2, 3, 2, 2, 0, 2,
       2, 2, 2, 2, 2, 2, 0, 2, 2, 2, 2, 2, 0, 0, 2, 2, 2, 2, 3, 2, 2, 0,
       2, 0, 2, 0, 2, 2, 2, 2, 2, 0, 2, 2, 2, 0, 2, 2, 0, 2, 2, 2, 0, 2,
       2, 2, 0, 2, 2, 0, 2, 2, 2, 1, 1, 2, 2, 2, 0, 2, 2, 0, 3, 3, 0, 2,
       0, 2, 2, 2, 3, 2, 2, 0, 2, 2, 2, 2, 2, 0, 2,

In [32]:
cars_test=pd.read_csv(r"cars_test.csv",header=None)
cars_test.columns=['buying','maint','doors','persons','lug_boot','safety','classes']
cars_test["Pred"]= Y_pred
cars_test["Pred"]=cars_test["Pred"].map({0:"acc",1:"good",2:"unacc",3:"vgood"})

cars_test.head(10)

buying  maint  doors persons lug_boot safety classes   Pred
0    med  vhigh  5more       4    small    low   unacc  unacc
1  vhigh   high      2       2      big    med   unacc  unacc
2    low   high      2    more    small    low   unacc  unacc
3  vhigh  vhigh      3       2      big   high   unacc  unacc
4    low    med      4       4      med    med    good   good
5  vhigh    low      3    more      med    low   unacc  unacc
6   high    low  5more    more      med    med     acc    acc
7  vhigh    med      2       4      big   high     acc    acc
8   high  vhigh      4    more      big    low   unacc  unacc
9    low  vhigh      3       4    small   high     acc    acc

In [33]:
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

print(confusion_matrix(cars_test.classes,cars_test.Pred))
print(classification_report(cars_test.classes,cars_test.Pred))
print(accuracy_score(cars_test.classes,cars_test.Pred))

[[ 60   1   3   0]
 [  3  10   0   0]
 [  0   0 251   0]
 [  0   0   0  18]]
              precision    recall  f1-score   support

         acc       0.95      0.94      0.94        64
        good       0.91      0.77      0.83        13
       unacc       0.99      1.00      0.99       251
       vgood       1.00      1.00      1.00        18

    accuracy                           0.98       346
   macro avg       0.96      0.93      0.94       346
weighted avg       0.98      0.98      0.98       346

0.9797687861271677


In [34]:
from sklearn.ensemble import ExtraTreesClassifier

model = ExtraTreesClassifier(n_estimators=100, random_state=10,bootstrap=True)

model.fit(X_train,Y_train)

Y_pred=model.predict(X_test)

In [35]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

print(confusion_matrix(Y_test,Y_pred_new))
print(classification_report(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))

[[ 69   0   2   0]
 [  2  10   0   0]
 [  0   0 185   0]
 [  0   0   0   9]]
              precision    recall  f1-score   support

           0       0.84      0.90      0.87        71
           1       1.00      0.33      0.50        12
           2       0.96      0.99      0.98       185
           3       1.00      0.78      0.88         9

    accuracy                           0.93       277
   macro avg       0.95      0.75      0.81       277
weighted avg       0.93      0.93      0.93       277

0.9314079422382672


In [36]:
from sklearn.ensemble import RandomForestClassifier
model=RandomForestClassifier(n_estimators=100,random_state=10,bootstrap=True)
model.fit(X_train,Y_train)
Y_pred=model.predict(X_test)

In [37]:
print(confusion_matrix(Y_test,Y_pred_new))
print(classification_report(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))

[[ 69   0   2   0]
 [  2  10   0   0]
 [  0   0 185   0]
 [  0   0   0   9]]
              precision    recall  f1-score   support

           0       0.93      0.92      0.92        71
           1       0.89      0.67      0.76        12
           2       0.97      0.99      0.98       185
           3       1.00      1.00      1.00         9

    accuracy                           0.96       277
   macro avg       0.95      0.89      0.92       277
weighted avg       0.96      0.96      0.96       277

0.9602888086642599


In [38]:
from sklearn.ensemble import AdaBoostClassifier

adaboost_model = AdaBoostClassifier(base_estimator=DecisionTreeClassifier(random_state=10),n_estimators=100,random_state=10)#n_estiamtors = no. of 100 DT/bags

adaboost_model.fit(X_train,Y_train)
Y_pred=adaboost_model.predict(X_test)

In [39]:
print(confusion_matrix(Y_test,Y_pred_new))
print(classification_report(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))

[[ 69   0   2   0]
 [  2  10   0   0]
 [  0   0 185   0]
 [  0   0   0   9]]
              precision    recall  f1-score   support

           0       0.95      0.97      0.96        71
           1       0.89      0.67      0.76        12
           2       0.99      1.00      1.00       185
           3       1.00      1.00      1.00         9

    accuracy                           0.98       277
   macro avg       0.96      0.91      0.93       277
weighted avg       0.98      0.98      0.98       277

0.9783393501805054


In [40]:
from sklearn.ensemble import GradientBoostingClassifier
GradientBoosting_model = GradientBoostingClassifier(n_estimators=300,random_state=10)#n_estiamtors = no. of 100 DT/bags
GradientBoosting_model.fit(X_train,Y_train)
Y_pred=GradientBoosting_model.predict(X_test)

In [41]:
print(confusion_matrix(Y_test,Y_pred_new))
print(classification_report(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))

[[ 69   0   2   0]
 [  2  10   0   0]
 [  0   0 185   0]
 [  0   0   0   9]]
              precision    recall  f1-score   support

           0       0.99      1.00      0.99        71
           1       1.00      0.92      0.96        12
           2       1.00      1.00      1.00       185
           3       1.00      1.00      1.00         9

    accuracy                           1.00       277
   macro avg       1.00      0.98      0.99       277
weighted avg       1.00      1.00      1.00       277

0.9963898916967509


In [42]:
# pip install xgboost

In [43]:
from xgboost import XGBClassifier
XGB_model = XGBClassifier(n_estimators=100,random_state=10)
XGB_model.fit(X_train,Y_train)
Y_pred=XGB_model.predict(X_test)

In [44]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.svm import SVC
from sklearn.ensemble import VotingClassifier
from sklearn.neighbors import KNeighborsClassifier

In [45]:
# create the submodels
estimators=[]
#mode1-=LogoisticReegression()
model2 = DecisionTreeClassifier(criterion='gini',random_state=10)
estimators.append(('cart',model2))

model3=SVC(kernel="rbf",C=90,gamma=0.1)
estimators.append(('svm',model3))

model4=KNeighborsClassifier(n_neighbors=5,metric='euclidean')
estimators.append(('knn',model4))

In [46]:
# create ensemble model
ensemble =VotingClassifier(estimators)
ensemble.fit(X_train,Y_train)
Y_pred=ensemble.predict(X_test)
#pritnt(Y_pred)

In [47]:
print(confusion_matrix(Y_test,Y_pred_new))
print(classification_report(Y_test,Y_pred))
print(accuracy_score(Y_test,Y_pred))

[[ 69   0   2   0]
 [  2  10   0   0]
 [  0   0 185   0]
 [  0   0   0   9]]
              precision    recall  f1-score   support

           0       0.95      0.97      0.96        71
           1       1.00      0.67      0.80        12
           2       0.99      1.00      0.99       185
           3       1.00      1.00      1.00         9

    accuracy                           0.98       277
   macro avg       0.98      0.91      0.94       277
weighted avg       0.98      0.98      0.98       277

0.9783393501805054


In [48]:
#from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.ensemble import VotingRegressor, StackingRegressor
from sklearn.neighbors import KNeighborsRegressor

In [49]:
#create sub models
level0 = []
model1 = LogisticRegression()
level0.append(('log', model1))

model2 = DecisionTreeClassifier(criterion='gini',random_state=10)
level0.append(('cart', model2))

model3 = SVC(kernel='rbf',C=90,gamma=0.1)
level0.append(('svm', model3))

model4 = KNeighborsClassifier(n_neighbors=5,metric='euclidean')
level0.append(('knn',model4))

level1=LogisticRegression()

In [50]:
# model will be available as model_DecisionTree.txt